# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8246d8b1b991c05b314b65c2eea4dbe1851bf7224e085a3d432c9f32b3f94bc7cfdb46036249528075db5cd9b8410f840da8576d197fe4fcee64016f9d97dd6e

test:
  secret_key_base: 3f29a9c10612f62d372d72d91d24b48b6668637fd073d4eaa014728e6770faea99a0fac431c2763b1aabc05cfdcdd9a60bb7a1d750657fca8ad8e9d187e2dfb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
